version: '2'

services:
  frontend-vietnam:
    container_name: frontend-vietnam
    image: frontend-vietnam:0.0.1
    build: .
    volumes:
    - ./svelte:/app/svelte
    ports:
      - 7071:7071
    restart: always